server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: org.example.entity

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: org.example.controller, org.example.security.controller

jwt:
  secret: your-secret-key-must-be-very-very-very-long-at-least-256-bits
  expiration: 86400
  token-prefix: "Bearer "
  header: "Authorization"

logging:
  level:
    org.springframework.security: DEBUG
    org.example.security: DEBUG
    org.example.mapper: DEBUG