server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  main:
    allow-circular-references: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: org.example.entity
  mapper-locations: classpath*:/mapper/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: org.example.controller, org.example.security.controller

jwt:
  secret: your_jwt_secret_key_here_make_it_long_and_secure
  expiration: 86400000  # 24 hours in milliseconds
  token-prefix: "Bearer "
  header: "Authorization"

logging:
  level:
    org.springframework.security: DEBUG
    org.example.security: DEBUG
    org.example.mapper: DEBUG